### ISSUE TITLE
[BUG] Issues with custom values in printer notes

### ISSUE THREAD

**Issue by b-fitzpatrick** [sn4k3/UVtools#12]
In the LookupCustomValues method in SL1File.cs, it searches for the custom values by string with an underscore added (i.e., "LiftHeight_"). This fails, as it finds "BottomLiftHeight_" and uses that value. The same occurs for "LiftSpeed_".

Also, I haven't found the code yet, but when importing the printer notes, it appears to truncate decimals. For example, I have "BottomLiftHeight_8.5" in the printer notes, but in the PrinterNotes string, the ".5" is not present.

**Comment by sn4k3** [comment]
This affects which format? you trying convert SL1 to what format?

**Comment by b-fitzpatrick** [comment]
I'm converting to ChituBox format for an Elegoo Mars printer.

**Comment by sn4k3** [comment]
Ok i found the problem. Will be fixed on next release

**Comment by sn4k3** [comment]
![image](https://user-images.githubusercontent.com/113281/87812410-097bb180-c858-11ea-875f-f847c25bd9bf.png)
Fixed

**Comment by b-fitzpatrick** [comment]
Thanks! I'm compiling from source, so I'll pick it up when you commit.

**Comment by sn4k3** [comment]
> Thanks! I'm compiling from source, so I'll pick it up when you commit.

Here's the fix code if you want to compile it right now:

`public T LookupCustomValue<T>(string name, T defaultValue, bool existsOnly = false)
        {
            if (string.IsNullOrEmpty(PrinterSettings.PrinterNotes)) return defaultValue;
            string result = string.Empty;
            if(!existsOnly)
                name += '_';

            var lines = PrinterSettings.PrinterNotes.Split(new[] { "\\r\\n", "\\r", "\\n" },
                StringSplitOptions.RemoveEmptyEntries);

            for (var i = 0; i < lines.Length; i++)
            {
                var line = lines[i].Trim();
                if (!line.StartsWith(name)) continue;
                if (existsOnly || line == name) return "true".Convert<T>();
                var value = line.Remove(0, name.Length);
                for (int x = 0; x < value.Length; x++)
                {
                    char c = value[x];
                    if (!char.IsLetterOrDigit(c) && c != '.')
                    {
                        break;
                    }

                    result += c;
                }
            }

            return string.IsNullOrWhiteSpace(result) ? defaultValue : result.Convert<T>();
        }`

**Comment by b-fitzpatrick** [comment]
That fixes the first issue. The second issue obviously still exists.

**Comment by sn4k3** [comment]
> That fixes the first issue. The second issue obviously still exists.

Can you better describe it?
I test float values and they work ok to me

**Comment by b-fitzpatrick** [comment]
Sorry, my bad. It works properly. I had removed the 0.5 in my test .sl1 file.
